host: localhost
port: 2000
tm_port: 8000
seed: 0
car_num: 50
syn:
  fixed_delta_seconds: 0.05
substepping:
  max_substep_delta_time: 0.01
  max_substeps: 10
n_layers: 3
lr: 0.001
gamma: 0.5
buffer_size: 100000
hidden_dim: 1024
epoch: 50
sample_n: 8
training_n: 12
max_episode_length: 3000
